# Generated by Django 2.1.3 on 2019-02-19 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_contact_form'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact_Form',
            new_name='Contact',
        ),
    ]
