"""
Django settings for DjangoApi project.

Generated by 'django-admin startproject' using Django 2.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'm883i@k*08#5@bdb_6%j*ha_c0hl!--_89i%r-@bf_isx0&-*0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
   # 'DjangoApi.apps.SuitConfig',
    'jet_django', # jet-django api app
    'suit',                                                                               # if we only using suit package
    'django.contrib.admin',
    'django.contrib.auth',

    'django.contrib.sites',

    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'post',
    'users',
    'crispy_forms',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'DjangoApi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'DjangoApi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

#Default database of djnago is sqlite3 for testing purpose only

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}



# we can use our database either mysql or sql or mongodb
#DATABASES={
 #   'default':{
  #      'ENGINE':'django.db.backends.mysql',  #mysql phpmyadmin ...maria db
   #     'NAME':'db_name',  # database name or db name
    #    'USER':'root',
     #   'PASSWORD':'',
      #  'HOST':'localhost',
       # 'PORT':''
    #}
#}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS= (
    os.path.join(BASE_DIR,'static'),)

STATIC_ROOT=os.path.join(os.path.dirname(BASE_DIR),'static')

MEDIA_URL='/media/'

MEDIA_ROOT=(os.path.join(BASE_DIR,'media'))

CRISPY_TEMPLATE_PACK='bootstrap3'

LOGIN_REDIRECT_URL='posts:list'


#console email backend ...url will show on console screen at backend...
EMAIL_BACKEND='django.core.mail.backends.console.EmailBackend'

#for production purpose...
#EMAIL_BACKEND='django.core.mail.backends.smtp.EmailBackend'
#EMAIL_HOST='smtp.gmail.com'
#EMAIL_PORT= 587
#EMAIL_USE_TLS= True
#EMAIL_HOST_USER= 'shubhj4019@gmail.com'
#EMAIL_HOST_PASSWORD= 'Shubhamgmail121'
#DEFAULT_FROM_EMAIL='shubhj4019@gmail.com'


#EMAIL_HOST='localhost'
#EMAIL_PORT=1025


#social account allauth authentication backend settings...
AUTHENTICATION_BACKENDS=(
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

SITE_ID= 1


#django-suit settings

SUIT_CONFIG = {
    'ADMIN_NAME': 'BlogLog'
}